### ISSUE TITLE
Crash - Allocation failure

### ISSUE THREAD

**Issue by hyperbart** [FireDrunk/node-kninflux#6]
![image](https://cloud.githubusercontent.com/assets/2131310/23403533/ceae5316-fdb0-11e6-91f9-636ecc813164.png)

**Comment by FireDrunk** [comment]
Attempt to address this issue has been commited in: https://github.com/FireDrunk/node-kninflux/commit/3e64dd4c14ec8f544b5148281e4bbe209ae5ee92

Please verify if the problem persists.
